const affirmations: string[] = [
  "I am fearfully and wonderfully made. (Psalm 139:14)",
  "I can do all things through Christ who strengthens me. (Philippians 4:13)",
  "The Lord is my shepherd; I shall not want. (Psalm 23:1)",
  "I am more than a conqueror through Him who loved me. (Romans 8:37)",
  "God has plans for me, plans to prosper me and not to harm me. (Jeremiah 29:11)",
  "The joy of the Lord is my strength. (Nehemiah 8:10)",
  "I am the head and not the tail, above and not beneath. (Deuteronomy 28:13)",
  "God is for me, so who can be against me? (Romans 8:31)",
  "I have not been given a spirit of fear, but of power, love, and a sound mind. (2 Timothy 1:7)",
  "I am a child of God, and I am deeply loved. (1 John 3:1)",
  "I am the light of the world. (Matthew 5:14)",
  "I am more than a conqueror through Him who loves me. (Romans 8:37)",
  "The Lord is my rock and my fortress. (Psalm 18:2)",
  "God's grace is sufficient for me. (2 Corinthians 12:9)",
  "I am strong in the Lord and in the power of His might. (Ephesians 6:10)",
  "I am God's workmanship, created in Christ Jesus for good works. (Ephesians 2:10)",
  "I am loved with an everlasting love. (Jeremiah 31:3)",
  "I will not fear, for God is with me. (Isaiah 41:10)",
  "I am a new creation in Christ. (2 Corinthians 5:17)",
  "I am redeemed and forgiven in Christ. (Ephesians 1:7)",
  "The peace of God guards my heart and mind. (Philippians 4:7)",
  "I am anointed and empowered to do good works. (Acts 10:38)",
  "I am a citizen of heaven. (Philippians 3:20)",
  "I am seated with Christ in heavenly places. (Ephesians 2:6)",
  "I am a joint heir with Christ. (Romans 8:17)",
  "I am the righteousness of God in Christ. (2 Corinthians 5:21)",
  "I am a child of the light and not of darkness. (1 Thessalonians 5:5)",
  "I have the mind of Christ. (1 Corinthians 2:16)",
  "God has not given me a spirit of fear, but of power, love, and sound mind. (2 Timothy 1:7)",
  "I am more than a conqueror through Him who loved me. (Romans 8:37)",
  "The Lord will fight for me; I need only to be still. (Exodus 14:14)",
  "I will fear no evil, for God is with me. (Psalm 23:4)",
  "I am liberated in Christ. (John 8:36)",
  "I am uniquely designed by God. (Ephesians 2:10)",
  "I am nourished by His Word. (Matthew 4:4)",
  "I am chosen for His purpose. (1 Peter 2:9)",
  "I am embraced by grace. (Galatians 3:9)",
  "I am uplifted by His presence. (Isaiah 41:10)",
  "I am surrounded by His peace. (John 14:27)",
  "I am a source of blessing. (Genesis 12:2)",
  "I am hopeful for the future. (Romans 15:13)",
  "I am walking confidently in faith. (2 Corinthians 5:7)",
  "I am representing Christ. (2 Corinthians 5:20)",
  "I am called to bear fruit. (John 15:16)",
  "I am anointed and sealed by God. (2 Corinthians 1:21-22)",
  "I am fearlessly sustained by God. (Psalm 55:22)",
  "I am strengthened with all might. (Colossians 1:11)",
  "I am free from the law of sin and death. (Romans 8:2)",
  "I am accepted in the Beloved. (Ephesians 1:6)",
  "I am God's temple; His Spirit dwells in me. (1 Corinthians 3:16)",
  "I am joined to the Lord, one spirit. (1 Corinthians 6:17)",
  "I am seated in the heavenly places with Christ. (Ephesians 2:6)",
  "I am restored by God. (Psalm 71:20)",
  "I am strong in the Lord. (Ephesians 6:10)",
  "Jesus understands me. (Hebrews 4:15)",
  "Christ takes my anxiety on Himself. (1 Peter 5:7)",
  "I am a citizen of heaven. (Philippians 3:20)",
  "I am the apple of God's eye. (Psalm 17:8)",
  "I am complete in Christ. (Colossians 2:10)",
  "I am a temple of the Holy Spirit, bought with a price. (1 Corinthians 6:19-20)",
  "I have been made righteous in God's sight. (2 Corinthians 5:21)",
  "I am an heir of God and co-heir with Christ. (Romans 8:17)",
  "The Lord restores my soul. (Psalm 23:3)",
  "God is the strength of my heart and my portion forever. (Psalm 73:26)",
  "The Lord forgives all my sins and heals all my diseases. (Psalm 103:3)",
  "I will not fear, for the Lord is my healer. (Exodus 15:26)",
  "I am renewed day by day through God's Spirit. (2 Corinthians 4:16)",
  "God gives power to the faint and strengthens the weak. (Isaiah 40:29)",
  "The Lord binds up my wounds and heals my broken heart. (Psalm 147:3)",
  "He renews my youth like the eagle's. (Psalm 103:5)",
  "I trust in the Lord for my healing and restoration. (Jeremiah 17:14)",
  "The Lord directs my steps and establishes my ways. (Proverbs 16:9)",
  "The Spirit of truth guides me into all truth. (John 16:13)",
  "I acknowledge God in all my ways, and He directs my paths. (Proverbs 3:6)",
  "The Lord teaches me what is best for me. (Isaiah 48:17)",
  "I wait for the Lord, and He renews my strength. (Isaiah 40:31)",
  "I am confident that God will finish the good work He started in me. (Philippians 1:6)",
  "I am bold because the Lord is my helper. (Hebrews 13:6)",
  "God's grace is sufficient for me in every moment. (2 Corinthians 12:9)",
  "The Spirit of God within me gives me power, love, and a sound mind. (2 Timothy 1:7)",
  "God's Word will not return void; His promises will be fulfilled in my life. (Isaiah 55:11)",
  "The Lord makes everything beautiful in His time. (Ecclesiastes 3:11)",
  "I am a royal priesthood, a holy nation, God's special possession. (1 Peter 2:9)",
  "I am a tree planted by the rivers of water, bearing fruit in season. (Psalm 1:3)",
  "I am a vessel of honor, fit for the Master's use. (2 Timothy 2:21)",
  "I am a citizen of the Kingdom of God. (Colossians 1:13)",
  "I am a partaker of God's divine nature. (2 Peter 1:4)",
  "I am chosen and called by God. (1 Peter 2:9)",
  "I am the salt of the earth. (Matthew 5:13)",
  "I am a vessel of the Holy Spirit. (1 Corinthians 6:19)",
  "I am God's temple. (1 Corinthians 3:16)",
  "I am a beloved child of God. (Ephesians 1:4)",
  "I am safe and secure in God's arms. (Psalm 91:4)",
  "I am healed by the stripes of Jesus. (1 Peter 2:24)",
  "I am an heir to the promises of God. (Galatians 3:29)",
  "I am a participant in the divine nature. (2 Peter 1:4)",
  "I am a friend of God. (John 15:15)",
  "I am God's workmanship, created for good works. (Ephesians 2:10)",
  "I am never alone, for God is always with me. (Hebrews 13:5)",
  "I am a witness for Christ, called to share His love. (Acts 1:8)",
  "I am God's masterpiece, fearfully and wonderfully made. (Psalm 139:14)",
  "I am an ambassador for Christ. (2 Corinthians 5:20)",
  "I am equipped for every good work. (2 Timothy 3:17)",
  "I am anointed to heal the brokenhearted. (Luke 4:18)",
  "I am seated in heavenly places with Christ Jesus. (Ephesians 2:6)",
  "I am a conqueror in Christ Jesus. (Romans 8:37)",
  "I am free from condemnation in Christ. (Romans 8:1)",
  "I am God's temple and the Spirit of God dwells in me. (1 Corinthians 3:16)",
  "I am a citizen of heaven. (Philippians 3:20)",
  "I am an heir of God and a co-heir with Christ. (Romans 8:17)",
  "I am chosen by God, holy and dearly loved. (Colossians 3:12)",
  "I am a reflection of God's love and light. (Matthew 5:14)",
  "I am blessed to be a blessing. (Genesis 12:2)",
  "I am made in the image of God. (Genesis 1:26)",
  "I am secure in God's love for me. (Romans 8:39)",
  "I am more than a conqueror through Christ. (Romans 8:37)",
  "I am fearfully and wonderfully made in the image of God. (Psalm 139:14)",
  "I am a new creation in Christ. (2 Corinthians 5:17)",
  "I am an heir to God's promise. (Galatians 3:29)",
  "I am protected by God's angels. (Psalm 91:11)",
  "I am God's child and heir to the Kingdom. (Romans 8:17)",
  "I am called to live a life worthy of God's calling. (Ephesians 4:1)",
  "I am transformed by the renewing of my mind. (Romans 12:2)",
  "I am filled with the Holy Spirit. (Acts 1:8)",
  "I am always under God's protection. (Psalm 91:1-2)",
  "I am an overcomer by the blood of the Lamb and the word of my testimony. (Revelation 12:11)",
  "I am strong in the Lord and in the power of His might. (Ephesians 6:10)",
  "I am a servant of the Most High God. (Matthew 20:28)",
  "I am filled with God's peace that surpasses all understanding. (Philippians 4:7)",
  "I am a branch of the true vine, Jesus Christ. (John 15:5)",
  "I am anointed to do the works of God. (Acts 10:38)",
  "I am the apple of God's eye. (Psalm 17:8)",
  "I am a royal priesthood, a holy nation. (1 Peter 2:9)",
  "I am a citizen of the Kingdom of God. (Ephesians 2:19)",
  "I am called to walk in the light of God's truth. (1 John 1:7)",
  "I am a conqueror in Christ Jesus. (Romans 8:37)",
  "I am accepted by God in Christ. (Ephesians 1:6)",
];

export default affirmations;
